# https://github.com/pages-themes/slate
theme: jekyll-theme-slate

title: Photography
description:

markdown: kramdown

# Else links won't work
#plugins:
  #- "jekyll-github-metadata"
#url: https://kolypto.github.io
#baseurl: /doc-photography
#github: [metadata]
